model:
  # Path to the Ultravox STT+LLM model directory
  stt_llm_path: "models/ultravox"  
  # Voice identifier for Kokoro TTS synthesis
  tts_voice: "af_heart"  
  # Path to the SpeechBrain-based emotion classifier
  emotion_classifier_model: "models/emotion_classifier"  

# Device for model inference ('cuda' for GPU, 'cpu' for CPU)
device: "cuda"  

vad:
  # WebRTC VAD aggressiveness level (0–3)
  aggressiveness: 3  

# Sampling rate (Hz) for TTS audio output
tts_sample_rate: 24000  
