model:
  stt_llm_path: "models/ultravox"
  kokoro_model_path: "models/kokoro"
  tts_voice: "af_heart"
  emotion_classifier_model: "models/emotion_classifier"

device: "cuda"
vad:
  aggressiveness: 3
tts_sample_rate: 24000
